### ISSUE TITLE
Input Manager

### ISSUE THREAD

**Issue by AndrewHamel111** [AndrewHamel111/SISGameJam2023#9]
Neatly wrap whatever horrors await in managing the input of 4 Xbox controllers. It is unclear what the best choice is between the "old" and new input system. It will probably be easier either way to use the newer system, I'm sure it will have better support for multiple controllers.

I really like Jason Weimanns videos so I'll just drop this [here](https://www.youtube.com/watch?v=wjJa6oYNg4Y).

**Comment by madmanntis** [comment]
HIT, MAGIC1 and MAGIC2 are the buttons each player has

**Comment by paul-writes-code** [comment]
README will be updated with usage information due to unexpected complications.
